name: fk_haber
description: FK Haber App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  dynamic_theme: ^1.0.1
  google_fonts: ^1.1.1
  flutter_native_splash: ^0.1.9
  flutter_feather_icons: ^1.0.3
  shared_preferences: ^0.5.12+4
  webfeed:
    git: https://github.com/Adem68/webfeed.git
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  url_launcher: ^5.7.10
  cached_network_image: ^2.5.0
  keyboard_avoider: ^0.1.2
  flutter_form_builder: ^4.2.0
  share: ^0.6.5+4
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#9d1cff"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  image: assets/images/icon.png
  color: "9d1cff"
  android_disable_fullscreen: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/